services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
        target: development
      command: npm run start:dev
      ports:
        - '3000:3000'
      env_file:
        - .env
      volumes:
        - .:/usr/src/app

    database:
      depends_on:
        - api
      image: postgres:16.3
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
      ports:
        - '5432:5432'
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}